name:                DataStructures
version:             0.1.0.0
github:              "githubuser/DataStructures"
license:             BSD3
author:              "samini91"
maintainer:          "samini91@gmail.com"
copyright:           "2021"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/DataStructures#readme>

default-extensions:
  - TypeFamilies

dependencies:
- base
- aeson
- monad-control
- mtl
- containers
- vector
- bytestring
- utf8-string

library:
  source-dirs: src

executables:
  DataStructures-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - DataStructures

tests:
  DataStructures-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - DataStructures
    - tasty
    - tasty-quickcheck
    - tasty-smallcheck
    - tasty-hunit
